// Action types to be dispatched by the user
export const WEBSOCKET_BINARY_CONNECT = 'WEBSOCKET:BINARY_CONNECT';
export const WEBSOCKET_BINARY_DISCONNECT = 'WEBSOCKET:BINARY_DISCONNECT';
export const WEBSOCKET_BINARY_SEND = 'WEBSOCKET:BINARY_SEND';
// Action types dispatched by the WebSocket implementation
export const WEBSOCKET_BINARY_CONNECTING = 'WEBSOCKET:BINARY_CONNECTING';
export const WEBSOCKET_BINARY_OPEN = 'WEBSOCKET:BINARY_OPEN';
export const WEBSOCKET_BINARY_DISCONNECTING = 'WEBSOCKET:BINARY_DISCONNECTING';
export const WEBSOCKET_BINARY_CLOSED = 'WEBSOCKET:BINARY_CLOSED';
export const WEBSOCKET_BINARY_MESSAGE = 'WEBSOCKET:BINARY_MESSAGE';
